# Generated by Django 2.2 on 2019-04-27 13:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Назва контрагента')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенти',
            },
        ),
        migrations.CreateModel(
            name='IncomingLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_date', models.DateField(default=datetime.date.today, verbose_name='Дата реєстрації листа')),
                ('receiving_number', models.CharField(max_length=50, verbose_name='Реєстраційний номер')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='title.Counterparty', verbose_name='Відправник')),
            ],
            options={
                'verbose_name': 'Вхідний лист',
                'verbose_name_plural': 'Вхідні листи',
                'ordering': ['receiving_date'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_date', models.DateField(default=datetime.date.today, verbose_name='Дата реєстрації листа')),
                ('sending_number', models.CharField(max_length=50, verbose_name='Реєстраційний номер')),
                ('receiver', models.ManyToManyField(to='title.Counterparty', verbose_name='Отримувач')),
            ],
            options={
                'verbose_name': 'Вихідний лист',
                'verbose_name_plural': 'Вихідні листи',
                'ordering': ['sending_date'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Назва титулу')),
                ('type', models.CharField(choices=[('OB', "Титул об'єкта будівництва"), ('PVR', 'Титул на проектно-вишукуальні роботи')], max_length=3, verbose_name='Тип титулу')),
                ('ministry_agreement', models.BooleanField(default=True)),
                ('is_done', models.BooleanField(default=False, verbose_name='Виконано')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('entry_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата і час занесення в базу даних')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='title.Counterparty', verbose_name='Замовник')),
                ('incoming_letter', models.ManyToManyField(blank=True, null=True, to='title.IncomingLetter', verbose_name='Вхідний супрводжувальний лист')),
                ('outcoming_letter', models.ManyToManyField(blank=True, null=True, to='title.OutgoingLetter', verbose_name='Вихідний супроводжувальний лист')),
            ],
            options={
                'verbose_name': 'Титул',
                'verbose_name_plural': 'Титули',
                'ordering': ['entry_datetime', 'is_done'],
            },
        ),
    ]
