# Generated by Django 2.2 on 2019-04-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='outcoming_letter',
            new_name='outgoing_letter',
        ),
    ]
