# Generated by Django 2.2.2 on 2019-06-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-entry_datetime', 'is_done'], 'verbose_name': 'Титул', 'verbose_name_plural': 'Титули'},
        ),
    ]
