# Generated by Django 2.2.5 on 2019-09-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0002_auto_20190630_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.CharField(choices=[('OB', "Титул об'єкта будівництва"), ('PVR', 'Титул на проектно-вишукувальні роботи')], max_length=3, verbose_name='Тип титулу'),
        ),
    ]
