# Generated by Django 2.2 on 2019-04-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0002_auto_20190427_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='incoming_letter',
            field=models.ManyToManyField(blank=True, to='title.IncomingLetter', verbose_name='Вхідний супрводжувальний лист'),
        ),
        migrations.AlterField(
            model_name='title',
            name='outgoing_letter',
            field=models.ManyToManyField(blank=True, to='title.OutgoingLetter', verbose_name='Вихідний супроводжувальний лист'),
        ),
    ]
